version: '3.5'

services:
  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`db.etalon.local`)"
      #- "traefik.https.routers.whoami.rule=Host(`db.etalon.local`)"
      #- "traefik.http.routers.whoami.entrypoints=websecure"
      #- "traefik.http.routers.whoami.tls.certresolver=default"
    networks:
      - webgateway

networks:
  webgateway:
    external:
      name: invest_processors
...