---
version: '3'
services:
  nats1:
    image: synadia/jsm:nightly
    dns_search: example.net
    entrypoint: /nats-server
    command: --name nats1 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245,nats://nats3:4245 -p 4222 -m 8222
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
    - ./jetstream-cluster/nats1:/data

  nats2:
    image: synadia/jsm:nightly
    dns_search: example.net
    entrypoint: /nats-server
    command: --name nats2 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245,nats://nats3:4245 -p 4222 -m 8222
    ports:
      - 4223:4222
      - 8223:8222
    volumes:
    - ./jetstream-cluster/nats2:/data

  nats3:
    image: synadia/jsm:nightly
    dns_search: example.net
    entrypoint: /nats-server
    command: --name nats3 --cluster_name JSC --js --sd /data --cluster nats://0.0.0.0:4245 --routes nats://nats1:4245,nats://nats2:4245,nats://nats3:4245 -p 4222 -m 8222
    ports:
      - 4224:4222
      - 8224:8222
    volumes:
    - ./jetstream-cluster/nats3:/data
  nats-webui:
    image: sphqxe/nats-webui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nats-webui.rule=Host(`nats.wb.home.lan`)"
      - "traefik.http.routers.nats-webui.entrypoints=web"

  stan-webui:
    image: piotrpersona/nats-streaming-ui
    ports:
      - 8282:8282
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stan-webui.rule=Host(`stan.wb.home.lan`)"
      - "traefik.http.routers.stan-webui.entrypoints=web"
    environment:
       - STAN_URL=http://nats1:4222
       - STAN_MONITOR_URL=http://nats1:8222
       - STAN_CLUSTER=JSC

networks:
  default:
    external: true
    name: work_bench_network
