version: '3'

services:
  nats1:
    image: nats:2.6
    ports:
      - 4222:4222
      - 8222:8222
    command: -m 8222 --cluster nats://0.0.0.0:6222 --routes nats://nats3:6222 -js --name nats1 --cluster_name testNats
  nats2:
    image: nats:2.6
    ports:
      - 4223:4222
      - 8223:8222
    command: -m 8222 --cluster nats://0.0.0.0:6222 --routes nats://nats1:6222 -js --name nats2 --cluster_name testNats
  nats3:
    image: nats:2.6
    ports:
      - 4224:422
      - 8224:8222
    command: -m 8222 --cluster nats://0.0.0.0:6222 --routes nats://nats2:6222 -js --name nats3 --cluster_name testNats

  nats-webui:
    image: sphqxe/nats-webui
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.nats-webui.rule=Host(`nats.wb.home.lan`)"
      - "traefik.http.routers.nats-webui.entrypoints=web"

  stan-webui:
#    image: kuali/nats-streaming-console
    image: piotrpersona/nats-streaming-ui
    ports:
      - 8282:8282
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stan-webui.rule=Host(`stan.wb.home.lan`)"
      - "traefik.http.routers.stan-webui.entrypoints=web"
#      - "traefik.http.services.nats-webui.loadbalancer.server.port=8282"
#      - "traefik.http.routers.nats-webui.service=nats-webui"
    environment:
       - STAN_URL=http://nats1:4222
       - STAN_MONITOR_URL=http://nats1:8222
       - STAN_CLUSTER=testNats    

networks:
  default:
    external: true
    name: work_bench_network

#docker run -p 8282:8282 -e STAN_URL=http://nats-url:4222 -e STAN_MONITOR_URL=http://nats-url:8222 -e STAN_CLUSTER=test-cluster piotrpersona/nats-streaming-ui:latest